export const ghlProjects = [
{
  id: 1,
  title: 'Healthcare CRM Automation System',
  slug: 'healthcare-crm-automation-system',
  category: 'Healthcare Automation',
  platform: 'GoHighLevel',
  description:
    'Production-ready GoHighLevel implementation that automates the complete patient journey from inquiry through treatment completion using CRM workflows, appointment management, reminders, and pipeline automation.',

  technologies: [
    'GoHighLevel',
    'CRM',
    'Workflow Automation',
    'Appointment Management',
    'Email Automation',
    'SMS Automation',
    'Pipeline Management',
  ],

  featured: true,

  workflowImage:
    '/screenshots/ghl/healthcare-crm-automation-system/workflow.png',

  executionImage:
    '/screenshots/ghl/healthcare-crm-automation-system/architecture.png',

  coverImage:
  '/screenshots/ghl/healthcare-crm-automation-system/cover.png',

  video:
  '/screenshots/ghl/healthcare-crm-automation-system/demo.mp4',

  videoPoster:
  "/screenshots/ghl/healthcare-crm-automation-system/cover.png",

  challenge:
    'Healthcare clinics often rely on manual CRM updates, inconsistent appointment tracking, and repetitive administrative tasks, increasing the risk of missed follow-ups and operational inefficiencies.',

  solution:
    'Built a complete GoHighLevel automation system that manages the entire patient lifecycle through CRM workflows, appointment automation, automated reminders, internal notifications, and pipeline progression.',

  workflowSummary: [
    'Automated patient lead management',
    'CRM opportunity creation and updates',
    'Appointment confirmations and reminders',
    'Consultation and treatment tracking',
    'No-show and cancellation management',
    'Case closure automation',
  ],

  businessOutcome: [
    'Reduced manual CRM updates',
    'Standardized patient workflow',
    'Improved appointment communication',
    'Better operational visibility',
  ],
},
  {
    id: 2,
    title: 'Lead Nurture Drip Campaign',
    slug: 'lead-nurture-drip-campaign',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Nurtures new leads with a timed sequence of relevant messages and follow-ups.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: true,
    workflowImage: '/screenshots/ghl/lead-nurture-drip-campaign/workflow.png',
    executionImage: '/screenshots/ghl/lead-nurture-drip-campaign/execution-logs.png',
    challenge: 'New leads were not consistently followed up with, resulting in missed opportunities and uneven communication.',
    solution: 'Built a GoHighLevel drip automation that delivers timely nurture messages based on lead engagement.',
    workflowSummary: [
      'Trigger when a new lead enters the CRM',
      'Send an introductory email',
      'Wait before the next follow-up',
      'Send nurture content and a booking prompt',
      'Evaluate engagement before continuing the sequence',
    ],
    businessOutcome: ['Improved follow-up consistency', 'Reduced manual lead chasing', 'Increased booking opportunities'],
  },
  {
    id: 3,
    title: 'AI Lead Capture Workflow',
    slug: 'ai-lead-capture-workflow',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Captures, enriches, and routes incoming leads into the correct CRM workflow.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: true,
    workflowImage: '/screenshots/ghl/ai-lead-capture-workflow/workflow.png',
    executionImage: '/screenshots/ghl/ai-lead-capture-workflow/execution-logs.png',
    challenge: 'Incoming leads required manual review before they could be categorized and assigned to the right sales process.',
    solution: 'Built a GoHighLevel workflow that captures lead information, enriches it, and routes each contact automatically.',
    workflowSummary: [
      'Trigger when a lead submits an enquiry',
      'Capture contact details in the CRM',
      'Evaluate lead information for routing',
      'Apply the correct tags and pipeline stage',
      'Notify the assigned sales team member',
    ],
    businessOutcome: ['Improved lead response time', 'Standardized lead routing', 'Reduced manual data entry'],
  },
  {
    id: 4,
    title: 'Sales Pipeline Automation',
    slug: 'sales-pipeline-automation',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Automates pipeline movement, task creation, and notifications throughout the sales process.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: true,
    workflowImage: '/screenshots/ghl/sales-pipeline-automation/workflow.png',
    executionImage: '/screenshots/ghl/sales-pipeline-automation/execution-logs.png',
    challenge: 'Sales representatives manually updated pipeline stages and follow-up tasks, which led to inconsistent deal management.',
    solution: 'Built a GoHighLevel automation that coordinates pipeline updates, sales tasks, and team notifications.',
    workflowSummary: [
      'Trigger when a deal changes pipeline stage',
      'Update opportunity details',
      'Create the next follow-up task',
      'Send relevant customer communication',
      'Notify the internal sales team',
    ],
    businessOutcome: ['Improved pipeline visibility', 'Reduced administrative work', 'Created consistent sales follow-up'],
  },
  {
    id: 5,
    title: 'Lost Opportunity Recovery',
    slug: 'lost-opportunity-recovery',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Re-engages lost opportunities with targeted recovery messaging and sales follow-up.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: true,
    workflowImage: '/screenshots/ghl/lost-opportunity-recovery/workflow.png',
    executionImage: '/screenshots/ghl/lost-opportunity-recovery/execution-logs.png',
    challenge: 'Lost opportunities were often left without a structured re-engagement process or future follow-up plan.',
    solution: 'Built a GoHighLevel recovery automation that re-engages lost leads with targeted messaging and sales alerts.',
    workflowSummary: [
      'Trigger when an opportunity is marked as lost',
      'Apply a lost-opportunity tag',
      'Wait for the recovery interval',
      'Send a re-engagement message',
      'Create a task for sales follow-up when engagement occurs',
    ],
    businessOutcome: ['Recovered dormant opportunities', 'Standardized re-engagement efforts', 'Reduced missed follow-up'],
  },
  {
    id: 6,
    title: 'Missed Appointment Recovery',
    slug: 'missed-appointment-recovery',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Follows up with no-show contacts and guides them back to a rescheduled appointment.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: true,
    workflowImage: '/screenshots/ghl/missed-appointment-recovery/workflow.png',
    executionImage: '/screenshots/ghl/missed-appointment-recovery/execution-logs.png',
    challenge: 'Missed appointments required manual outreach, leaving many no-show contacts without a prompt path to reschedule.',
    solution: 'Built a GoHighLevel automation that follows up with no-shows and directs them to rebook their appointment.',
    workflowSummary: [
      'Trigger when an appointment is marked as no-show',
      'Update the contact with a missed-appointment tag',
      'Send a rescheduling message',
      'Wait before sending a reminder',
      'Notify the team if the contact does not rebook',
    ],
    businessOutcome: ['Improved appointment recovery', 'Reduced manual no-show follow-up', 'Increased rebooking opportunities'],
  },
  {
    id: 7,
    title: 'Proposal Automation',
    slug: 'proposal-automation',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Delivers proposals after sales calls and sends timely reminders to keep deals moving.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: false,
    workflowImage: '/screenshots/ghl/proposal-automation/workflow.png',
    executionImage: '/screenshots/ghl/proposal-automation/execution-logs.png',
    challenge: 'Proposal delivery and follow-up relied on manual reminders, allowing prospects to go cold after sales calls.',
    solution: 'Built a GoHighLevel automation that sends proposals and schedules follow-up reminders after each sales call.',
    workflowSummary: [
      'Trigger after a completed sales call',
      'Send the proposal to the prospect',
      'Wait for the proposal review period',
      'Send a follow-up reminder',
      'Create a sales task if there is no response',
    ],
    businessOutcome: ['Accelerated proposal delivery', 'Improved follow-up consistency', 'Reduced stalled opportunities'],
  },
  {
    id: 8,
    title: 'Appointment Rescheduled Workflow',
    slug: 'appointment-rescheduled-workflow',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Updates appointment records and communicates the new schedule to the right people.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: false,
    workflowImage: '/screenshots/ghl/appointment-rescheduled-workflow/workflow.png',
    executionImage: '/screenshots/ghl/appointment-rescheduled-workflow/execution-logs.png',
    challenge: 'Rescheduled appointments required manual record updates and notifications, increasing the risk of scheduling errors.',
    solution: 'Built a GoHighLevel workflow that updates appointment data and informs both contacts and internal teams automatically.',
    workflowSummary: [
      'Trigger when an appointment is rescheduled',
      'Update the appointment record',
      'Send the new appointment details to the contact',
      'Notify the assigned team member',
      'Send a reminder before the new appointment time',
    ],
    businessOutcome: ['Reduced scheduling errors', 'Improved client communication', 'Kept internal teams informed'],
  },
  {
    id: 9,
    title: 'Sales Discovery Call Automation',
    slug: 'sales-discovery-call-automation',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Coordinates confirmation, reminders, and post-call follow-up for discovery appointments.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: false,
    workflowImage: '/screenshots/ghl/sales-discovery-call-automation/workflow.png',
    executionImage: '/screenshots/ghl/sales-discovery-call-automation/execution-logs.png',
    challenge: 'Discovery calls had inconsistent confirmation, reminder, and post-call follow-up processes.',
    solution: 'Built a GoHighLevel automation that manages communication before and after each sales discovery call.',
    workflowSummary: [
      'Trigger when a discovery call is booked',
      'Send booking confirmation',
      'Send timed appointment reminders',
      'Update the opportunity after the call',
      'Launch the appropriate post-call follow-up',
    ],
    businessOutcome: ['Improved show-up rates', 'Standardized discovery-call follow-up', 'Reduced sales administration'],
  },
  {
    id: 10,
    title: 'Stop Lead Nurture After Booking',
    slug: 'stop-lead-nurture-after-booking',
    category: 'CRM Automation',
    platform: 'GoHighLevel',
    description: 'Stops nurture messages once a lead books, preventing duplicate or irrelevant communication.',
    technologies: ['GoHighLevel', 'CRM', 'Automation'],
    featured: false,
    workflowImage: '/screenshots/ghl/stop-lead-nurture-after-booking/workflow.png',
    executionImage: '/screenshots/ghl/stop-lead-nurture-after-booking/execution-logs.png',
    challenge: 'Leads continued receiving nurture messages after booking, creating duplicate and irrelevant communication.',
    solution: 'Built a GoHighLevel automation that removes booked contacts from the nurture sequence immediately.',
    workflowSummary: [
      'Trigger when a lead books an appointment',
      'Check whether the contact is in a nurture workflow',
      'Remove the contact from active nurture campaigns',
      'Apply a booked-appointment tag',
      'Start appointment confirmation communication',
    ],
    businessOutcome: ['Prevented duplicate messages', 'Improved prospect experience', 'Kept nurture workflows accurate'],
  },
] as const;
